trigger:
 - main
  
resources:
  - repo: self
  
variables:
  azureSubscription: 'VMS ARM SC NRG'
  webAppName: 'vms-dev-webclient'
  vmImageName: 'ubuntu-latest'
  dev-url: https://vms-dev-webclient.azurewebsites.net
  
stages:
- stage: Build
  displayName: Build Angular App
  jobs:
  - job: Build
    displayName: Build Angular App
    pool:
      vmImage: $(vmImageName)
  
    steps:
    - task: NodeTool@0
      displayName: 'Install Node.js'
      inputs:
        versionSpec: '20.x'
  
    - script: npm install
      displayName: Install npm packages
  
    - script: npm run build -- --configuration=production
      displayName: Build Angular project
  
    - task: ArchiveFiles@2
      displayName: 'Archive Build Output'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true
  
    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop
      displayName: Publish Build Artifact
  
- stage: Deploy_Development
  displayName: Deploy to Development
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - deployment: Deploy
    displayName: Deploy to Development
    environment: Development
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - download: none
          - task: DownloadPipelineArtifact@2
            displayName: 'Download Build Artifacts'
            inputs:
              artifactName: 'drop'
              downloadPath: '$(Pipeline.Workspace)/drop'
  
          - script: ls -R $(Pipeline.Workspace)
            displayName: 'Debug: List Pipeline Workspace'
  
          - task: AzureWebApp@1
            displayName: 'Deploy to Development'
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webAppLinux
              appName: $(webAppName)
              #packageForLinux: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
              deploymentMethod: 'zipDeploy'              
              startUpCommand: 'pm2 serve /home/site/wwwroot/dist/vms-project-web --spa --no-daemon'
  
          - task: CmdLine@2
            displayName: Confirm Deployment
            inputs:
              script: 'curl -sSf $(dev-url) > /dev/null'
              failOnStderr: true